config/routes.rb
AmoebaCircus::Application.routes.draw do
  resources :amoebas
  get '/amoebas/:id/split' => 'amoebas#split'

  get '/acts' => 'acts#index'
  post '/acts' => 'acts#create'
  get '/acts/new' => 'acts#new', as: "new_act"
  get '/acts/:id/edit' => 'acts#edit', as: "edit_act"
  get '/acts/:id' => 'acts#show', as: "act"
  put '/acts/:id' => 'acts#update'
  delete '/acts/:id' => 'acts#destroy'

end

app/models/act.rb
class Act < ActiveRecord::Base
  attr_accessible :name, :date, :time
  has_many :act_amoebas
  has_many :amoebas, :through => :act_amoebas
  has_many :talents, :through => :amoebas # may need a through act_amoebas as well
end

app/models/act_amoeba.rb
class ActAmoeba < ActiveRecord::Base
  attr_accessible :amoeba_id, :act_id
  belongs_to :act
  belongs_to :amoeba
end

app/models/amoeba.rb
class Amoeba < ActiveRecord::Base
  attr_accessible :name, :generation, :talent_id
  belongs_to :talent
  has_many :act_amoebas
  has_many :acts, :through => :act_amoebas

  def jr1
    origin = self.name
    "#{origin[0].next}#{origin[1..-2]}f"
  end

  def jr2
    origin = self.name
    "#{origin[0].next.next}#{origin[1..-2]}s"
  end

  def split
    Amoeba.create(:name=>jr1, :generation=>(generation+1), :talent_id=>talent_id)
    Amoeba.create(:name=>jr2, :generation=>(generation+1), :talent_id=>talent_id)
    destroy
  end

end

app/models/talent.rb
class Talent < ActiveRecord::Base
  attr_accessible :name
  has_many :amoebas
  has_many :acts, :through => :amoebas # may need middle man here (act_amoebas)
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController

  def index
    @acts = Act.all
  end

  def new
    @act = Act.new
  end

  def create
    @act = Act.new
    p = params[:act]
    @act.name = p[:name]
    @act.date = Date.parse("#{p["date(3i)"]}/#{p["date(2i)"]}/#{p["date(1i)"]}")
    @act.time = Time.parse("#{p["time(4i)"]}:#{p["time(5i)"]}")
    p[:amoebas][1..-1].each do |amoeba_id|
      @act.amoebas << Amoeba.find(amoeba_id)
    end
    @act.save
    redirect_to @act
  end

  def show
    @act = Act.find(params[:id])
  end

  def edit
    @act = Act.find(params[:id])
  end

  def update
    @act = Act.find(params[:id])
    p = params[:act]
    @act.name = p[:name]
    @act.date = Date.parse("#{p["date(3i)"]}/#{p["date(2i)"]}/#{p["date(1i)"]}")
    @act.time = Time.parse("#{p["time(4i)"]}:#{p["time(5i)"]}")
    p[:amoebas][1..-1].each do |amoeba_id|
      next if @act.amoebas.include? Amoeba.find(amoeba_id)
      @act.amoebas << Amoeba.find(amoeba_id)
    end
    @act.save
    redirect_to @act
  end

  def destroy
    Act.find(params[:id]).destroy
    redirect_to '/acts'
  end

end

app/controllers/amoebas_controller.rb
class AmoebasController < ApplicationController

  def index
    @amoebas = Amoeba.all
  end

  def new
    @amoeba = Amoeba.new
  end

  def create
    @amoeba = Amoeba.create(params[:amoeba])
    redirect_to @amoeba
  end

  def show
    @amoeba = Amoeba.find(params[:id])
  end

  def edit
    @amoeba = Amoeba.find(params[:id])
  end

  def update
    @amoeba = Amoeba.find(params[:id])
    @amoeba.update_attributes(params[:amoeba])
    redirect_to @amoeba
  end

  def destroy
    Amoeba.find(params[:id]).destroy
    redirect_to '/amoebas'
  end

  def split
    Amoeba.find(params[:id]).split
    redirect_to '/amoebas'
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/amoebas_helper.rb
module AmoebasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/views/acts/_form.html.haml
= form_for(@act) do |f|
  
  .field
    = f.label :name
    %br
    = f.text_field :name
    %br
    = f.date_select :date, :order=>[:month, :day, :year]
    %br
    = f.time_select :time, {:ampm=>true}
    %br
    = f.label :amoebas
    %br
    = f.collection_select :amoebas, Amoeba.all, :id, :name, {}, {:multiple => :true} # get the talent next to the name
  .actions
    = f.submit

app/views/acts/edit.html.haml
%h1 Edit Act

= render "form"

= link_to "Back", acts_path

app/views/acts/index.html.haml
%h1 Acts

%table
  %tbody
    %tr
      %th Name
      %th Date
      %th Time
      %th Actions
    - @acts.each do |act|
      %tr
        %td= act.name
        %td= act.date.strftime("%m/%d/%Y")
        %td= act.time.strftime("%l:%M%p")
        %td
          = link_to "Show", "/acts/#{act.id}"
          = link_to "Edit", "/acts/#{act.id}/edit"
          = link_to "Destroy", "/acts/#{act.id}", :method => :delete, data: { confirm: 'Are you sure?' }
    %br

= link_to "New", new_act_path

app/views/acts/new.html.haml
%h1 New Act

= render "form"

= link_to "Back", acts_path

app/views/acts/show.html.haml
%h1
  = @act.name

%p= @act.date.strftime("Date: %m/%d/%Y")
%p= @act.time.strftime("Time: %l:%M%p")
%table
  %h4 Amoebas in this Act:
  %tr
    %th Name
    %th Talent
  - @act.amoebas.each do |amoeba|
    %tr
      %td= link_to "#{amoeba.name}", "/amoebas/#{amoeba.id}"
      %td= "#{amoeba.talent.name}"

%br
= link_to "Edit", edit_act_path
= link_to "Destroy", "/acts/#{@act.id}", :method => :delete, data: { confirm: 'Are you sure?' }
%br

= link_to "Back", acts_path

app/views/amoebas/_form.html.haml
= form_for(@amoeba) do |f|
  
  .field
    = f.label :name
    %br
    = f.text_field :name
    %br
    = f.label :talent
    %br
    = f.collection_select :talent_id, Talent.all, :id, :name
    %br
  .actions
    = f.submit

app/views/amoebas/edit.html.haml
%h1 Edit Amoeba

= render "form"

= link_to "Back", amoebas_path

app/views/amoebas/index.html.haml
%h1 Amoebas

%table
  %tbody
    %tr
      %th Name
      %th Generation
      %th Talent
      %th Actions
    - @amoebas.each do |amoeba|
      %tr
        %td= amoeba.name
        %td= amoeba.generation
        %td= amoeba.talent.name
        %td
          = link_to "Show", "/amoebas/#{amoeba.id}"
          = link_to "Edit", "/amoebas/#{amoeba.id}/edit"
          = link_to "Split", "/amoebas/#{amoeba.id}/split"
          = link_to "Destroy", "/amoebas/#{amoeba.id}", :method => :delete, data: { confirm: 'Are you sure?'}
    %br

= link_to "New", new_amoeba_path

app/views/amoebas/new.html.haml
%h1 New Amoeba

= render "form"

= link_to "Back", amoebas_path

app/views/amoebas/show.html.haml
%h1
  = @amoeba.name
%p
  Generation:
  = @amoeba.generation
%p
  Talent:
  = @amoeba.talent.name
%p
  Acts I'm in:
  - @amoeba.acts.each do |act|
    %br
    = link_to "#{act.name}", "/acts/#{act.id}"
%br
= link_to "Edit", edit_amoeba_path
= link_to "Split", "/amoebas/#{@amoeba.id}/split"
= link_to "Destroy", "/amoebas/#{@amoeba.id}", :method => :delete, data: { confirm: 'Are you sure?' }
%br

= link_to "Back", amoebas_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmoebaCircus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>